apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-service-monitor
  labels:
    app: acit3495          # not sure what to label this
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka    # matching labels in prometheus?
  namespaceSelector:
    matchNames:
      - monitoring  # this is the namespace of our kafka cluster
  endpoints:
  - port: metrics
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-kube-state-metrics
      replacement: $1
      action: keep
  - port: metrics
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-node-exporter
      replacement: $1
      action: keep
