global:
    scrape_interval:    5s # By default, scrape targets every 15 seconds.
    evaluation_interval: 10s # Evaluate rules every 15 seconds.

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets:
      - '34.122.79.44:8080'
